# Generated by Django 2.2.13 on 2021-06-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Updates',
        ),
    ]
