# Generated by Django 2.2.13 on 2021-06-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_delete_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateTitle', models.CharField(max_length=50)),
                ('updateDescription', models.CharField(max_length=50)),
                ('updateDates', models.DateField()),
            ],
        ),
    ]
