# Generated by Django 2.2.13 on 2021-06-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210616_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('numberOfGuest', models.IntegerField(max_length=50)),
                ('bookDate', models.DateField()),
            ],
        ),
    ]
