# Generated by Django 2.2.13 on 2021-06-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='numberOfGuest',
            field=models.IntegerField(),
        ),
    ]
